---
mig_operator_location: "{{ workspace }}/mig-operator"
mig_operator_repo: "{{ lookup('env', 'MIG_OPERATOR_REPO') or 'https://github.com/fusor/mig-operator.git' }}"
mig_operator_branch: "{{ lookup('env', 'MIG_OPERATOR_BRANCH') or 'master' }}"
mig_operator_release: "{{ lookup('env', 'MIG_OPERATOR_RELEASE') or 'latest' }}"
mig_operator_use_olm: "{{ lookup('env', 'MIG_OPERATOR_USE_OLM') or 'false' }}"
mig_operator_use_downstream: "{{ lookup('env', 'MIG_OPERATOR_USE_DOWNSTREAM') or 'false' }}"
mig_operator_selector: { '4.1': 'marketplace.catalogSourceConfig=ocpmigrate-operators', '4.2': 'marketplace.operatorSource=ocpmigrate-operators', 'nightly': 'marketplace.operatorSource=ocpmigrate-operators', '4.3': 'marketplace.operatorSource=ocpmigrate-operators', 'latest-4.1': 'marketplace.catalogSourceConfig=ocpmigrate-operators', 'latest-4.2': 'marketplace.operatorSource=ocpmigrate-operators', 'latest': 'marketplace.operatorSource=ocpmigrate-operators' }
mig_controller_location: "{{ workspace }}/mig-controller"
mig_controller_repo: "{{ lookup('env', 'MIG_CONTROLLER_REPO') or 'https://github.com/fusor/mig-controller.git' }}"
mig_controller_branch: "{{ lookup('env', 'MIG_CONTROLLER_BRANCH') or 'master' }}"
mig_controller_sa_name: mig
mig_controller_host_cluster: true
mig_controller_velero: true
mig_controller_ui: true
mig_controller_remote_cluster_online: true
mig_migration_namespace: openshift-migration
rh_sub_user: "{{ lookup('env', 'SUB_USER') }}"
rh_sub_pass: "{{ lookup('env', 'SUB_PASS') }}"
rh_downstream_registry: "registry.redhat.io"
