---
- name: Include required vars
  include_vars:
    file: "{{ playbook_dir }}/roles/mig_controller_prereqs/defaults/main.yml"

- name: Destroy migration namespace
  k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ mig_migration_namespace }}"
    wait: yes
    wait_timeout: 300

- name: Destroy velero CRDs
  k8s:
    state: absent
    api_version: v1beta1
    kind: CustomResourceDefinition
    name: "{{ item }}"
    wait: yes
  with_items: "{{ velero_crds }}"

- name: Destroy cluster role bindings
  k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    name: "{{ item }}"
    wait: yes
  with_items: "{{ mig_cluster_role_bindings }}"

- name: Destroy manager cluster role
  k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    name: manager-role
    wait: yes

- name: Destroy s3 bucket if present
  include: destroy_s3_bucket.yml
